Fix issue with `asset_ids` in `create-catalog`
stactools-packages/threedep pull request #15
Opened 2023-07-21 15:34 UTC by hrodmn

**Related Issue(s):**
Resolves #14 

**Description:**
Rather than overwriting `asset_ids` variable when running the first collection, conditionally loop through `asset_ids` or `utils.fetch_ids(product)` to make sure you are not running `asset_ids` from one product on the other!

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [ ] Code lints properly (run `scripts/lint`).
  - this is failing due to a typing issue in `stactools.core`, I think?
  
  ```
  $ scripts/lint
    mypy.....................................................................Failed
    - hook id: mypy
    - exit code: 1
    
    tests/test_commands.py:14: error: Class cannot subclass "CliTestCase" (has type "Any")  [misc]
    Found 1 error in 1 file (checked 10 source files)
  ``` 
- [x] Tests pass (run `scripts/test`).
- [ ] Documentation has been updated to reflect changes, if applicable.
- [x] Changes are added to the [CHANGELOG](../CHANGELOG.md).

2023-08-04 20:28 UTC, gadomski requested changes
Looks fine to me, the PR just needs to be updated with **main** to pick up #16, which I can't do b/c I don't have permissions on https://github.com/ncx-co/threedep. In the future, it can be easier if you create a branch on your fork for the PR -- that allows me to make minor fixup changes if needed.

Thanks for the contribution!

2023-08-04 20:28 UTC, gadomski commented on src/stactools/threedep/stac.py
> +    assert isinstance(item, Item)
```suggestion
```

Should be unnecessary after updating with #16

2023-08-08 11:08 UTC, hrodmn commented
> Looks fine to me, the PR just needs to be updated with **main** to pick up #16, which I can't do b/c I don't have permissions on https://github.com/ncx-co/threedep.

I rebased my branch to get the latest changes, should be good to go now!

> In the future, it can be easier if you create a branch on your fork for the PR -- that allows me to make minor fixup changes if needed.

Ah I see. So instead of pushing changes to `main` on my forked copy, just push changes to a branch and open a PR to the upstream repo?

2023-08-08 12:11 UTC, gadomski commented
> Ah I see. So instead of pushing changes to main on my forked copy, just push changes to a branch and open a PR to the upstream repo?

Yup, that makes it easier to (a) open multiple PRs from your fork, if you'd like to, and (b) repo maintainers (e.g. me) to push changed to your branch.

2023-08-08 12:11 UTC, gadomski approved these changes

2023-08-08 17:01 UTC, merged